pagopa/pagopa-ecommerce-payment-methods-service

.devops/deploy-pipelines.yml
Dockerfile
helm/.helmignore
helm/Chart.lock
helm/Chart.yaml
helm/values-dev.yaml
pom.xml
src/main/resources/application.properties

- add deploy pipeline with helm chart;
- add health check endpoints with spring actuator;
The goal of this PR is to create a pipeline to deploy the service on the `ecommerce` AKS namespace.

[CHK-433] deploy pipeline

---

api-spec/api.yaml
src/main/java/it/pagopa/ecommerce/payment/instruments/application/PspService.java
src/main/java/it/pagopa/ecommerce/payment/instruments/controller/PaymentInstrumentsController.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/PspRepository.java

- Add query param for ` GET /payment-instruments/psps`
- Support search by amount and/or language
- Local docker build/run

[CHK-474] Add query param for payment-instruments/psps

---

api-spec/api.yaml
src/main/java/it/pagopa/ecommerce/payment/instruments/application/PspService.java
src/main/java/it/pagopa/ecommerce/payment/instruments/controller/PaymentInstrumentsController.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/PspRepository.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/AmountFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/AmountIdFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/AmountLangFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/AmountLangIdFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/AmountLangTypeIdFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/AmountTypeFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/AmountTypeIdFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/AmountTypeLangFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/FilterRuleEngine.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/IFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/IdFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/LangIdFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/LangTypeIdFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/NoFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/TypeFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/TypeIdFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/TypeLangFilterRule.java
src/test/java/it/pagopa/ecommerce/payment/instruments/infrastructure/rule/FilterRuleEngineTests.java
src/test/java/it/pagopa/ecommerce/payment/instruments/service/PspServiceTests.java

- Add GET `/idPaymentInstrument/psps?amount&lang`
- Update filters

[CHK-442] feat: Add paymentInstrumentId filter

---

CODEOWNERS
Dockerfile
applicationinsights.json
helm/values-dev.yaml
helm/values-uat.yaml

[CHK-679] add appinsights for payment methods

---

helm/values-uat.yaml

feat: apiconfig-uat

---

api-spec/api.yaml
src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
src/main/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethod.java
src/main/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethodFactory.java
src/main/java/it/pagopa/ecommerce/payment/methods/domain/valueobjects/PaymentMethodAsset.java
src/main/java/it/pagopa/ecommerce/payment/methods/domain/valueobjects/PaymentMethodRange.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/PaymentMethodDocument.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/PspRepository.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/rule/AmountFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/rule/AmountLangFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/rule/AmountTypeFilterRule.java
src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethodFactoryTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/infrastructure/rule/FilterRuleEngineTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java

- Add asset reference to pagopa CDN
- Solve bug on amount filter rule

[CHK-702] Add asset field for PaymentMethod aggregate

---

src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java

[CHK-702] fix: amount filter for PaymentMethodRange

---

src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/PspRepository.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/rule/AmountTypeLangFilterRule.java
src/test/java/it/pagopa/ecommerce/payment/methods/infrastructure/rule/FilterRuleEngineTests.java

[CHK-702] fix: amount and language filter bug

---

helm/values-uat.yaml

Resource tuning and scaling policy based on CPU
This modification is needed in order to handle autoscalign correctly
Tested through soak tests

feat: tuning + autoscaling

---

.devops/azure-templates/maven-github-release.yml
.devops/deploy-pipelines.yml
helm/Chart.yaml
helm/values-dev.yaml
helm/values-uat.yaml
pom.xml

1. Fixed condition checks into maven-github-release.yml template file
2. Make modification to perform release based on chart version instead of the applicative version (the pom.xml ones).
If deploy pipeline is run with the `none` as the version bump strategy to be used no version is increased into the pom. Because of an erroneous condition check on the above parameter the bump version task is performed anyway causing the task itself to go into a freeze state since no version update is specified to the 
`mvn build-helper:parse-version versions:set` command and in this case an input is expected on the standard input causing the pipeline to freeze in this state.
Test performed executing the pipeline in UAT environment (the maven github release template is executed only in UAT environment …

[CHK-753] fix maven Github release template

---

src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
src/main/java/it/pagopa/ecommerce/payment/methods/application/PspService.java
src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
src/main/java/it/pagopa/ecommerce/payment/methods/domain/valueobjects/PaymentMethodRange.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/PaymentMethodDocument.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/PspDocument.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/PspRepository.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/rule/AmountFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/rule/AmountLangFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/rule/AmountTypeFilterRule.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/rule/AmountTypeLangFilterRule.java
src/test/java/it/pagopa/ecommerce/payment/methods/infrastructure/rule/FilterRuleEngineTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/PspServiceTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java

Changed amounts type from BigInteger.
Since BigInteger can manipulate arbitrary large numbers this type is mapped to a String into mongo documents.
This cause that queries that perform comparations such as greater/less than perform a literal comparation instead of the wanted numerical one.
Using long as integer numerical fields force document field to be stored as a numerical ones and fixes comparations
Local test

Chk 952 fix amount filter

---

helm/Chart.lock
helm/Chart.yaml
helm/values-dev.yaml
helm/values-uat.yaml

- update AKS microservice helm chart to v2
This PR updates the current microservice Helm chart to the latest version, v2.3.1

CHK-982-chart-v2 update chart V2 

---

api-config-mock/Dockerfile.api-config-mock
docker-compose.yml
gec-mock/Dockerfile.gec-mock
gec-mock/api-config-server.json
gec-mock/middleware.js
gec-mock/routes.json

Added new json-server **gec-mock** .
Added new json server mock useful for integration with GEC.

CHK-1185-GEC-json-server-mock

---

src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java

Changes to the code after the GEC swagger changes were applied.
The change was necessary because the list of pspId strings in input to GEC became a list of objects. Therefore, the changes were applied for proper handling.
The tests were performed locally.

fix_changes_swagger_GEC

---

.devops/azure-templates/chart-current-version.yml
.devops/azure-templates/helm-microservice-chart-deploy.yml
.devops/azure-templates/maven-github-release.yml
.devops/deploy-pipelines.yml

Modified deploy pipeline to add configuration for skipping blue/green deployment
Modified deploy pipeline to add configuration for skipping blue/green deployment

fix: skip blue/green deployment

---

.devops/azure-templates/maven-github-release.yml
api-spec/api.yaml
src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java

Depends on: https://github.com/pagopa/pagopa-infra/pull/830 (INFRA)
- Open api review: add missing information such as contact, DR link etc
- Changed `POST /payment-methods/{id}/fee/calculate` to `POST /payment-methods/{id}/fees` indicating the GET with body description message
- Removed openapi descriptor version upgrade task since API version is not linked to application version and every update will be done manually and will not follow applicative version
Those modifications are needed in order to let API stick to the shared guidelines
Junit tests

fix: review open api specs

---

docker-compose.yml
src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java

- Add `null` value handling for bundle paymentType
- The `null` value is considered as ANY value in the afm domain, to embrace this logic the null value of paymentType is converted to the requested one by the client.

[CHK-1321] fix: null paymentTypeCode bundle handling

---

.devops/deploy-pipelines.yml

Add microservice template in case of skip blue/green deploy
Add microservice template in case of skip blue/green deploy

fix: deploy pipeline in case of skip blue/green deploy

---

helm/values-uat.yaml

fix: afm endpoint for uat

---

.devops/azure-templates/api-tests.yml
.devops/deploy-pipelines.yml

This PR update the devops deploy pipeline adding two new steps of API tests to test the integration of the deployed microservice in the eCommerce environment. The stages test the development deployment, the blue UAT deployment and the green UAT deployment. 
- Add API integration tests in deploy pipeline
- Increase code quality

[CHK-1386] feat: add integration test stage for deploy pipeline

---

api-spec/api.yaml
src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java

This reverts commit #44 
Restore GET payment-methods response body removing the array as root object
This modification is needed in order to be compliant with API guidelines.
Note: the implementation to handle this response has already been made in Checkout f.e. and checkout-be-mock
Junit tests + local tests

restore get payment methods object response body

---

.devops/azure-templates/api-tests.yml

[CHK-1386] fix: error on deploy pipeline

---

helm/values-prod.yaml

feat(helm): CHK-1539 Add value for prod

---

.devops/code-review-pipelines.yml

- Add publish test result on code review devops pipeline
- Add coverage overview in sonarcloud dashboard

[CHK-1546] fix: add code coverage on azure devops

---

src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
src/main/java/it/pagopa/ecommerce/payment/methods/mdcutilities/MDCContextLifter.java
src/main/java/it/pagopa/ecommerce/payment/methods/mdcutilities/MDCContextLifterConfiguration.java
src/main/java/it/pagopa/ecommerce/payment/methods/mdcutilities/MDCFilter.java
src/main/resources/logback.xml
src/test/java/it/pagopa/ecommerce/payment/methods/mdcutilities/MDCContextLifterTests.java

The PR implements the "Context per MDC" solution useful for correlating logs by header **transactionId** passed as input in POST request fees.
The change was made to allow correlation of logs via transactionId when retrieving bundles from **GEC**.
The tests were performed locally.

CHK-1558-log-transactionid

---

.identity/00_locals.tf
.identity/02_application_main.tf

Restore resources with var, excluding locals

Fix opex dashboard resources

---

.identity/02_application_main.tf

Fix subject on opex dashboard creation

fix opex subject

---

.github/workflows/create_dashboard.yaml

Fix creat dashboard remove uat

Remove uat from create_dashboard.yaml

---

.devops/deploy-pipelines.yml
api-spec/api.yaml
src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
src/main/java/it/pagopa/ecommerce/payment/methods/client/AfmClient.java
src/test/java/it/pagopa/ecommerce/payment/methods/client/AfmClientTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java

[CHK-1614] add query param allCCP to gec api

---

helm/values-prod.yaml
helm/values-uat.yaml

Enabling autoscaling for UAT and PROD environments
Enabling autoscaling for UAT and PROD environments
Performance tests

 [CHK-1641] feat: enable autoscaling

---

helm/values-prod.yaml

feat: enable log prod

---

.devops/deploy-pipelines.yml
.github/actions/check-pr-semver-labels/action.yml
.github/workflows/check_pr.yaml
.github/workflows/deploy.yml
README.md

Add github action that check for the presence of well-formed tags that will be used to trigger semantic versioning parameters for deploy module once PR is merge on main branch.
Those tags are:
| Tag                | Semantic versioning scope | Meaning                                                           |
|--------------------|---------------------------|-------------------------------------------------------------------|
| patch              | Application version       | Patch-bump application version into pom.xml and Chart app version |
| minor              | Application version       | Minor-bump application version into pom.xml and Chart app version |
| major              | Application version       | Major-bump application version into pom.xml and Chart app version |
| …

feat(CD): deploy on PR merge

---

.devops/deploy-pipelines.yml

Fix api test condition
Fix api test condition

fix(deploy-pipeline): uat api test condition

---

.github/actions/check-pr-semver-labels/action.yml

Fix pr extraction number
Fix pr extraction number

fix: pr extraction number from commit message

---

api-spec/api.yaml
src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java

Depends on https://github.com/pagopa/pagopa-infra/pull/1156
Add payment method description field into calculate fee response
Add payment method description field into calculate fee response
Junit tests

[CHK-1707] - feat(calculate-fees): add payment method description

---

Dockerfile
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

* use OpenTelemetry monitoring agent instead of Elastic APM

[CHK-1590] feat(tracing): use OpenTelmetry agent instead of Elastic APM

---

helm/values-prod.yaml

Enable OpenTelemetry log sending for PROD env
Enable OpenTelemetry log sending for PROD env

fix: enable open telemetry log sending

---

.env.example
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
src/main/java/it/pagopa/ecommerce/payment/methods/config/NpgWebClientsConfig.java
src/main/resources/application.properties
src/test/resources/application.test.properties

* rename env var `NPG_KEY` -> `NPG_API_KEY`
This PR renames the NPG API Key with a name that is more consistent with eCommerce guidelines.

[CHK-1782] refactor(env): rename env var `NPG_KEY` -> `NPG_API_KEY`

---

api-spec/api.yaml
pom.xml
src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java

[CHK-1734] feat(api): add endpoint for creating form for a payment method

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

* fix integer keys into config maps to string keys
Integer values are not allowed into k8s `ConfigMap`s.

fix(config): fix integer values into config maps to string values

---

api-spec/api.yaml
pom.xml
src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java

depend on https://github.com/pagopa/pagopa-ecommerce-commons/pull/119
👉🏻 Added logic for invoke NGP for retrieve card data using sessionId 
👉🏻 Added tests for new logic
👉🏻 Added new api into openapi specification
The change was made to allow the recovery of the **card bin** during the payment flow.
The tests was performed locally

feat(read card data): CHK-1817 added new endpoint for read card data by NPG

---

helm/values-prod.yaml
helm/values-uat.yaml

Fixed npg variable for uat and prod env
The change was made to correct for the variables in the rudder value

fix(helm value): fixed helm value npg variable for uat and prod

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

Fixed secret name for np api key

fix(helm value): fixed secret name for npg api key from npg-key to npg-api-key

---

src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
src/main/java/it/pagopa/ecommerce/payment/methods/exception/SessionIdNotFoundException.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/CardDataDocument.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/NpgSessionDocument.java
src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java

👉🏻 Added logic to cache card data received from **NPG**.
The change was made to allow the caching of the values ​​returned by the NPG during card information retrieval.

feat(retrieve card data) CHK 1828 cache value

---

pom.xml
src/main/java/it/pagopa/ecommerce/payment/methods/config/NpgWebClientsConfig.java
src/test/java/it/pagopa/ecommerce/payment/methods/client/NpgWebClientConfigTest.java
src/test/java/it/pagopa/ecommerce/payment/methods/client/NpgWebClientTestConfig.java

[CHK-1787] feat(commons): update commons version

---

pom.xml
src/main/resources/application.properties

Added redis dependency into pom.xml
Added into application.properties redis.host value

fix(dependency) added redis dependency

---

api-spec/api.yaml
src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
src/main/java/it/pagopa/ecommerce/payment/methods/exception/InvalidSessionException.java
src/main/java/it/pagopa/ecommerce/payment/methods/exception/MismatchedSecurityTokenException.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/NpgSessionDocument.java
src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java

* add endpoint to validate NPG session data
This PR adds and endpoint to validate session data when receiving a payment outcome notification from NPG.
Depends on #92

[CHK-1836] feat(api): add endpoint to validate session with id and security token

---

api-spec/api.yaml
helm/values-dev.yaml
src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
src/main/java/it/pagopa/ecommerce/payment/methods/exception/SessionAlreadyAssociatedToTransaction.java
src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java

* add endpoint to associate NPG session to trnsaction id
Depends on #93

[CHK-1839] feat(sessions): add endpoint to associate NPG session to transaction id

---

.devops/code-review-pipelines.yml

Fixed collection folder position into ecommerce local used into CR pipeline

Chk 1871 fixed context path folder tests

---

helm/values-dev.yaml

* increase CPU request and limit for dev environment
Increased CPU limits after AKS node downgrade for DEV env

feat(deploy): increase CPU request and limit for dev environment

---

helm/values-dev.yaml

Use UAT GEC for dev env
Use UAT GEC for dev env

chore(conf): [CHK-1901] - use uat GEC for dev env

---

helm/values-prod.yaml
helm/values-uat.yaml

Increase initialDelays for UAT and PROD environments
Increase initialDelays for UAT and PROD environments

fix: increase initial delay

---

.devops/deploy-pipelines.yml

Perform end to end test after module deploy in DEV and UAT environment
Perform end to end test after module deploy in DEV and UAT environment
Deploy pipeline execution

feat(test): [CHK-1999] add end-to-end-test after deploy

---

pom.xml

* update `pagopa-ecommerce-commons` version to 0.26.0
Ordinary maintenance

chore(deps): [CHK-2004] - update `commons` version to 0.26.0

---

helm/values-prod.yaml
helm/values-uat.yaml

Increase prod CPU limit
Limit increased due to service required start resource

fix: increase prod limit

---

src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
src/main/java/it/pagopa/ecommerce/payment/methods/utils/UniqueIdUtils.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/utils/UniqueIdUtilsTests.java

For the generation of the unique orderId and contractId for NPG I thought to proceed from the timestamp in milliseconds by concatenating random way N characters between URI safe alphanumeric values.
I ruled out concurrency problems in generating the two ids in the same millisecond through a probability calculation described as follows.
Consider the length of the timestamp string in milliseconds = 13
So the random string to be generated will be 18 (maximum length of the unique id) - 13 = 5 characters
Suppose we have 2000 RPS on the service (very large number of requests) so 2 requests per millisecond.
The number of alphanumeric characters used to generate the random string is 65.
```
const val ALPHANUMERICS: String =
"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._"
``` …

CHK-2087: feat: added UniqueId generation for orderId

---

src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java

* add error handling for NPG client in controller
Added missing error handling for NPG errors

[CHK-2103] fix(npg): add error handling for NPG client in controller

---

helm/values-prod.yaml

- set minReplica to 3 for prod env, one for availability zone;
- add antiPodAffinity with[ topology.kubernetes.io/zone](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone);
The goal of this PR is to increase the availability  by deploying at least one pod per availability zone.

feat: Chk 2075 podAntiAffinity

---

src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
src/main/java/it/pagopa/ecommerce/payment/methods/exception/NoBundleFoundException.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java

Fix no bundle found exception handling
Previous logic uses input mono request inside switch if empty but it is no more available when exception handling take place causing 400 error code being returned (caused by request body no more available) instead of proper 404 error code
Local test with eCommerce local + junit tests + test in dev environment

fix: no bundle found exception handling

---

helm/values-prod.yaml

feat: add npg prod config

---

src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java

* add missing `NpgResponseException` in controller error handler annotation
Added new unit test

fix(controller): add missing exception to error handler annotation for `NpgResponseException`

---

api-spec/api.yaml

set method management mandatory in response body
set method management mandatory in response body in api definition

[CHK-2312] feat(method management): set method management mandatory in response body

---

docker-compose.yml
src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
src/main/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsController.java
src/main/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethod.java
src/main/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethodFactory.java
src/test/java/it/pagopa/ecommerce/payment/methods/controller/PaymentMethodsControllerTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethodFactoryTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethodTest.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java

* `PaymentMethod.npgPaymentMethod` is now initialized only for NPG-managed methods (i.e. for `REDIRECT` is `null`)
* Added invariant to `PaymentMethod`: if management is set to `REDIRECT` then the type code must be `REDIRECT` and vice-versa
This PR fixes a bug where `PaymentMethod.npgPaymentMethod` would be initialized even for redirect methods, leading to a `IllegalArgumentException`, making redirect method creation through the API impossible
Depends on pagopa/pagopa-ecommerce-local#125
**Note for reviers**: Should I add an ad-hoc exception or is `IllegalArgumentException` ok?

[CHK-2322] fix(redirect): add handling of redirect methods during method creation

---

helm/values-prod.yaml

feat: CHK-1987 disable log sending from apm agent (elk)

---

pom.xml

Fix afm openapi github ref
Fix afm openapi github ref
Local build

feat: set gec openapi ref to main branch commit

---

pom.xml

[CHK-2595] update gec openapi ref

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
src/main/resources/application.properties

This PR adds a new deployment strategy by setting maxSurge to 1 and maxUnavailable to 0. Also setup spring boot's graceful shutdown.
- set maxSurge to 1 and maxUnavailable to 0. In this way running pods keeps active and only one new pod at time is started
- enabled spring boot graceful shutdown by setting it on application.properties file. Also extended the gracefull windows to 25 seconds
- explicitly set k8s graceful period to 30 seconds
To improve reliability and availability during deployments. This changes allows to:
- to start one pod at time
- to gracefully stops receiving requests when a pod stop is requested (graceful shutdown)
- stops progressively old pods when new ones are ready
Tested on dev with 3 replicas

[CHK-2631] Add new deployment strategy

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

The goal of this PR is to also add the Redis hostname as a secret, allowing the synchronization of the reference to the new Redis password with any potential hostname updates.

refactor(redis): use new redis config

---

src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodService.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/PaymentMethodServiceTests.java

Value NPG `correlationId` in GET cardData api call with the build session one
This modification is needed in order to correlate all NPG api calls belonging to the same transaction (using transaction associated correlationId)
Junit tests + test in DEV environment

fix(monitoring): correlation id for GET card data

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
src/main/resources/application.properties
src/main/resources/logback-spring.xml

- enable conf to configure log level
The goal of this PR is to add a configuration to control the log level of the application (`SERVICE_LOGGING_LEVEL`), and that of the entire service including dependencies (`ROOT_LOGGING_LEVEL`).

feat(log): enable conf to configure log level

---

helm/values-dev.yaml

feat: handle beta version for notification url

---

api-spec/v1/api.yaml
src/main/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethod.java

Update methodManagement domain for payment method document
Update api definition for paymentMethod.
The `methodManagement` field in payment method collection now has this domain
- `REDIRECT` for method to be handled with redirect path
- `NOT_ONBOARDABLE` for method to be handled with NPG, available only for guest payment, not for onboarding 
- `ONBOARDABLE_ONLY` for method to be handled with NPG, available only for onboarding and payment as onboarded method, not for guest payment
- `ONBOARDABLE` for method to be handled with NPG, available for onboarding, payment as onboarded method, and guest payment
- `ONBORDABLE_WITH_PAYMENT` for method to be handled with NPG, available for onboarding, payment as onboarded method, guest payment and onboarding at the same time as payment
This PR has the …

[CHK-2840] feat(method-management): add more values for method management

---

src/main/java/it/pagopa/ecommerce/payment/methods/config/WebClientsConfig.java

Configure Netty DNS resolver to use 1 as number of dots in name resolution
This modification is a porting of the fix performed [here](https://github.com/pagopa/pagopa-ecommerce-payment-methods-service/pull/191) and applied to all clients
Test in UAT env (during performance tests)

fix: ndots

---

src/main/java/it/pagopa/ecommerce/payment/methods/controller/v1/PaymentMethodsController.java
src/main/java/it/pagopa/ecommerce/payment/methods/controller/v2/PaymentMethodsController.java

* add exception logging in controllers

[CHK-2954] fix: add exception logging in controllers

---

helm/values-prod.yaml

chore(helm): increase min replicas to 5

---

src/main/java/it/pagopa/ecommerce/payment/methods/domain/enumerations/RedirectPaymentMethodTypeCode.java
src/test/java/it/pagopa/ecommerce/payment/methods/domain/aggregates/PaymentMethodFactoryTests.java

Add handling for iConto RICO redirect payment type code
Add handling for iConto RICO redirect payment type code
Test in DEV environment

fix: add RICO redirect payment type code

---

api-spec/v1/api.yaml
api-spec/v2/api.yaml
pom.xml
src/main/java/it/pagopa/ecommerce/payment/methods/application/v1/PaymentMethodService.java
src/main/java/it/pagopa/ecommerce/payment/methods/application/v2/PaymentMethodService.java
src/main/java/it/pagopa/ecommerce/payment/methods/controller/v1/PaymentMethodsController.java
src/main/java/it/pagopa/ecommerce/payment/methods/controller/v2/PaymentMethodsController.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/v2/PaymentMethodServiceTests.java

- Updated open api V1 to include an optional header for language preference
- Updated ecommerce-common reference to 1.26.0 
- after merge with https://github.com/pagopa/pagopa-ecommerce-payment-methods-service/pull/227: The language header is now sent to the 3rd party APIS (npg client)
This change is part of a bigger task aiming to provide NPG with the language preference as set by the user on the checkout FE. 
Unit test

[CHK-3244] Update open api v2 to include an optional "lang" header

---

src/main/java/it/pagopa/ecommerce/payment/methods/mdcutilities/MDCContextLifter.java
src/main/java/it/pagopa/ecommerce/payment/methods/mdcutilities/MDCFilter.java
src/test/java/it/pagopa/ecommerce/payment/methods/mdcutilities/MDCContextLifterTests.java

- put only transactionId value into MDC from reactor context
- clear MDC if reactor flow complete
- remove contextKey with related copy from mdc to reactor
The goal of this PR is to reduce logging size to decrease cost.
Unit test

[CHK-3345] feat: reduce logging size

---

.devops/deploy-pipelines.yml

Fix the api tests refs for deploy pipeline

fix: set right api test refs

---

src/main/java/it/pagopa/ecommerce/payment/methods/application/v1/PaymentMethodService.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/v1/PaymentMethodServiceTests.java
src/test/java/it/pagopa/ecommerce/payment/methods/utils/TestUtil.java

- add t queryparam with timestamp in milliseconds into createSession url
The goal of this PR is to prevent index.html caching by append random queryparam to redirect urls
Unit test

feat: add random queryparam into return url

---

README.md
helm/values-prod.yaml
src/main/resources/application.properties

This reverts commit 9e8d05e97bb92b06dd778976c47fb08c627aa9ac.

[PIDM] Revert "[CHK-4234] chore(mongo): add replica set to mongo connection"

---

.devops/code-review-pipelines.yml
dep-sha256.json
pom.xml
src/main/java/it/pagopa/ecommerce/payment/methods/application/PaymentMethodServiceCommon.java
src/main/java/it/pagopa/ecommerce/payment/methods/application/v1/PaymentMethodService.java
src/main/java/it/pagopa/ecommerce/payment/methods/config/RedisConfig.java
src/main/java/it/pagopa/ecommerce/payment/methods/config/UniqueIdConfiguration.java
src/main/java/it/pagopa/ecommerce/payment/methods/infrastructure/NpgSessionsTemplateWrapper.java
src/test/java/it/pagopa/ecommerce/payment/methods/service/v1/PaymentMethodServiceTests.java

Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/253
Use reactive redis templates
Use reactive redis templates
junit + local tests using eCommerce local

feat: use reactive redis templates

---

Dockerfile

- add the missing step to copy the generated sha256 file for dependencies verification
In a previous PR we introduced the dependencies verification flow. This PR addresses a problem that fix some pipelines step.

fix: step copy sha256 file in dockerfile

---

.devops/deploy-pipelines.yml

- Migrated DEV and UAT build stages from inline Docker commands to use centralized `azure-pipeline-templates/templates/docker-release/template.yaml`
- Added proper GitHub token file creation for Docker build secrets
- Configured `DOCKER_BUILD_ARGS` parameter to pass GitHub token as Docker secret
The current pipeline implementation uses inline Docker build commands with duplicated logic across multiple services. This approach has several issues:
1. **Code Duplication**: Each service reimplements the same Docker build logic
2. **Maintenance Overhead**: Changes to build process require updates across all services
3. **Inconsistency**: Different services may have slight variations in build commands
This change standardizes all services to use the centralized `azure-pipeline-templates` …

feat: restore template usage and add token file creation
